#!/bin/sh
# Validate a commit message against docs/COMMIT.md.
# Usage: check-commit-msg.sh [--label <text>] <file> | --stdin
set -eu

usage() {
    echo "usage: $0 [--label <text>] <file> | --stdin" >&2
    exit 2
}

_label=""
if [ "${1-}" = "--label" ]; then
    _label=" [$2]"
    shift 2
fi

if [ "${1-}" = "--stdin" ]; then
    msg=$(cat)
elif [ "${#}" -eq 1 ]; then
    msg=$(cat "$1")
else
    usage
fi

# Normalise line endings and encoding before any validation:
# - strip CR (CRLF from Windows editors or GitHub PR body)
# - strip UTF-8 BOM if present (Windows Notepad / some VS Code configs)
# - strip trailing whitespace from every line (editors often pad Why:/Proof:)
# Then drop comment lines and trailing blank lines at EOF.
msg=$(printf '%s\n' "$msg" \
  | tr -d '\r' \
  | sed '1s/^\xef\xbb\xbf//' \
  | sed 's/[[:space:]]*$//' \
  | sed '/^#/d' \
  | sed -e :a -e '/^[[:space:]]*$/{$d;N;ba' -e '}')

if [ -z "$msg" ]; then
    echo "check-commit-msg${_label}: empty message" >&2
    exit 1
fi

fail() {
    echo "check-commit-msg${_label}: $1" >&2
    exit 1
}

first=$(printf '%s\n' "$msg" | sed -n '1p')
second=$(printf '%s\n' "$msg" | sed -n '2p')

printf '%s' "$first" | grep -q $'[\xE2\x80\x94]' && fail "em-dash in first line"
printf '%s\n' "$msg" | grep -q $'[\xE2\x80\x94]' && fail "em-dash in message"
printf '%s\n' "$msg" | grep -qiE 'co-authored-by:.*(claude|copilot|chatgpt|anthropic|openai|cursor|codex|grok)' && \
    fail "assistant Co-Authored-By trailer"
printf '%s\n' "$msg" | grep -qiE 'generated with|generated by (claude|copilot|chatgpt|an? ai)' && \
    fail "generator attribution"

len=$(printf '%s' "$first" | wc -c | tr -d ' ')
[ "$len" -le 72 ] || fail "first line is ${len} chars (max 72)"

printf '%s' "$first" | grep -Eq '^[a-z]+\([a-z0-9-]+\): ' || \
    fail "first line must be type(scope): subject"
printf '%s' "$first" | grep -q '\.$' && fail "subject must not end with a period"

type=${first%%(*}
scope=${first#*(}
scope=${scope%%):*}

case "$type" in
    feat|fix|perf|refactor|test|build|ci|docs|chore) ;;
    *) fail "unknown type '$type'" ;;
esac

case "$scope" in
    match|format|corr|contrib|simd|fuzz|cli|build|github|docs) ;;
    *) fail "unknown scope '$scope'" ;;
esac

[ -z "$second" ] || fail "line 2 must be blank"

printf '%s\n' "$msg" | grep -qx 'Why:' || fail "missing Why: section"
printf '%s\n' "$msg" | grep -qx 'Proof:' || fail "missing Proof: section"
printf '%s\n' "$msg" | grep -Eq '^Contract: (none|abi|format|wire)$' || \
    fail "missing or invalid Contract: line (none|abi|format|wire)"

# Why: must be followed by a non-empty line that is not another header.
why_next=$(printf '%s\n' "$msg" | awk 'BEGIN{h=0} /^Why:$/{h=1; next} h==1{print; exit}')
[ -n "$why_next" ] || fail "Why: is empty"
case "$why_next" in
    Proof:|Contract:*) fail "Why: is empty" ;;
esac

proof_next=$(printf '%s\n' "$msg" | awk 'BEGIN{h=0} /^Proof:$/{h=1; next} h==1{print; exit}')
[ -n "$proof_next" ] || fail "Proof: is empty"
case "$proof_next" in
    Contract:*) fail "Proof: is empty" ;;
esac
if printf '%s' "$proof_next" | grep -qx 'not run:'; then
    fail "Proof: 'not run:' needs a reason"
fi

echo "check-commit-msg${_label}: ok"
